include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = BatteryUKRMPrefs
BatteryUKRMPrefs_FILES = BUKRootListController.m
BatteryUKRMPrefs_FRAMEWORKS = UIKit
BatteryUKRMPrefs_PRIVATE_FRAMEWORKS = Preferences
BatteryUKRMPrefs_INSTALL_PATH = /Library/PreferenceBundles
BatteryUKRMPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
